# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0003_auto_20170322_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='dojosecrets.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
